--CASHB01P25
Delete from custom.c_cpmaster where PARAMETER_ID = 'CASHBACK_WD' and BANK_ID = 'BAZMX';
Delete from custom.c_cpvalue where PARAMETER_ID = 'CASHBACK_WD' and BANK_ID = 'BAZMX';
Insert into custom.c_cpmaster (MODULE_NAME,PARAMETER_LEVEL,PARAMETER_ID,PARAMETER_DESC,PARAMETER_TYPE,QUERY_ID,LIST_TYPE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('LIABILITIES','BNKL','CASHBACK_WD','CashBack withdrawal at business',
null,null,'FT','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX');
Insert into custom.c_cpvalue (PARAMETER_ID,LEVELCODE_1,LEVELCODE_2,PARAMETER_VALUE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('CASHBACK_WD',null,null,'CASHB01P25','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX');
--CCASH02P25
Delete from custom.c_cpmaster where PARAMETER_ID = 'CANCELCASHBACK_WD' and BANK_ID = 'BAZMX';
Delete from custom.c_cpvalue where PARAMETER_ID = 'CANCELCASHBACK_WD' and BANK_ID = 'BAZMX';
Insert into custom.c_cpmaster (MODULE_NAME,PARAMETER_LEVEL,PARAMETER_ID,PARAMETER_DESC,PARAMETER_TYPE,QUERY_ID,LIST_TYPE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('LIABILITIES','BNKL','CANCELCASHBACK_WD','Cancellation of a Cashback withdrawal at business',
null,null,'FT','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX');
Insert into custom.c_cpvalue (PARAMETER_ID,LEVELCODE_1,LEVELCODE_2,PARAMETER_VALUE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('CANCELCASHBACK_WD',null,null,'CCASH02P25','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX');
