--COMBZ01P25
Delete from custom.c_cpmaster where PARAMETER_ID = 'BAZCOM_PUR' and BANK_ID = 'BAZMX';
Delete from custom.c_cpvalue where PARAMETER_ID = 'BAZCOM_PUR' and BANK_ID = 'BAZMX';
Insert into custom.c_cpmaster (MODULE_NAME,PARAMETER_LEVEL,PARAMETER_ID,PARAMETER_DESC,PARAMETER_TYPE,QUERY_ID,LIST_TYPE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('LIABILITIES','BNKL','BAZCOM_PUR','BAZ Com Purchases',
null,null,'FT','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX');
Insert into custom.c_cpvalue (PARAMETER_ID,LEVELCODE_1,LEVELCODE_2,PARAMETER_VALUE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('BAZCOM_PUR',null,null,'COMBZ01P25','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX');
--COMRD01P25
Delete from custom.c_cpmaster where PARAMETER_ID = 'REDCOM_PUR' and BANK_ID = 'BAZMX';
Delete from custom.c_cpvalue where PARAMETER_ID = 'REDCOM_PUR' and BANK_ID = 'BAZMX';
Insert into custom.c_cpmaster (MODULE_NAME,PARAMETER_LEVEL,PARAMETER_ID,PARAMETER_DESC,PARAMETER_TYPE,QUERY_ID,LIST_TYPE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('LIABILITIES','BNKL','REDCOM_PUR','RED Com Purchases',
null,null,'FT','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX');
Insert into custom.c_cpvalue (PARAMETER_ID,LEVELCODE_1,LEVELCODE_2,PARAMETER_VALUE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('REDCOM_PUR',null,null,'COMRD01P25','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX');
--COMEX01P25
Delete from custom.c_cpmaster where PARAMETER_ID = 'FOREIGN_PUR' and BANK_ID = 'BAZMX';
Delete from custom.c_cpvalue where PARAMETER_ID = 'FOREIGN_PUR' and BANK_ID = 'BAZMX';
Insert into custom.c_cpmaster (MODULE_NAME,PARAMETER_LEVEL,PARAMETER_ID,PARAMETER_DESC,PARAMETER_TYPE,QUERY_ID,LIST_TYPE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('LIABILITIES','BNKL','FOREIGN_PUR','Foreign Purchases',
null,null,'FT','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX');
Insert into custom.c_cpvalue (PARAMETER_ID,LEVELCODE_1,LEVELCODE_2,PARAMETER_VALUE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('FOREIGN_PUR',null,null,'COMEX01P25','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX');
--DCCOMEEP25
Delete from custom.c_cpmaster where PARAMETER_ID = 'FOREIGN_PUR_LOSS' and BANK_ID = 'BAZMX';
Delete from custom.c_cpvalue where PARAMETER_ID = 'FOREIGN_PUR_LOSS' and BANK_ID = 'BAZMX';
Insert into custom.c_cpmaster (MODULE_NAME,PARAMETER_LEVEL,PARAMETER_ID,PARAMETER_DESC,PARAMETER_TYPE,QUERY_ID,LIST_TYPE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('LIABILITIES','BNKL','FOREIGN_PUR_LOSS','Foreign Exchange Loss',
null,null,'FT','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX');
Insert into custom.c_cpvalue (PARAMETER_ID,LEVELCODE_1,LEVELCODE_2,PARAMETER_VALUE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('FOREIGN_PUR_LOSS',null,null,'DCCOMEEP25','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX');
--DCCOMEIP25
Delete from custom.c_cpmaster where PARAMETER_ID = 'FOREIGN_PUR_GAIN' and BANK_ID = 'BAZMX';
Delete from custom.c_cpvalue where PARAMETER_ID = 'FOREIGN_PUR_GAIN' and BANK_ID = 'BAZMX';
Insert into custom.c_cpmaster (MODULE_NAME,PARAMETER_LEVEL,PARAMETER_ID,PARAMETER_DESC,PARAMETER_TYPE,QUERY_ID,LIST_TYPE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('LIABILITIES','BNKL','FOREIGN_PUR_GAIN','Foreign Exchange Gain',
null,null,'FT','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX');
Insert into custom.c_cpvalue (PARAMETER_ID,LEVELCODE_1,LEVELCODE_2,PARAMETER_VALUE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('FOREIGN_PUR_GAIN',null,null,'DCCOMEIP25','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX');
COMMIT; 