Delete from custom.c_cpmaster where PARAMETER_ID = 'POS_ADQUIRENTE_REQUEST' and BANK_ID = 'BAZMX'
/
Delete from custom.c_cpvalue where PARAMETER_ID = 'POS_ADQUIRENTE_REQUEST' and BANK_ID = 'BAZMX'
/
Insert into custom.c_cpmaster (MODULE_NAME,PARAMETER_LEVEL,PARAMETER_ID,PARAMETER_DESC,PARAMETER_TYPE,QUERY_ID,LIST_TYPE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('LIABILITIES','BNKL','POS_ADQUIRENTE_REQUEST','Debit Card JSON Request Path',
null,null,'FT','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX')
/
Insert into custom.c_cpvalue (PARAMETER_ID,LEVELCODE_1,LEVELCODE_2,PARAMETER_VALUE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('POS_ADQUIRENTE_REQUEST',null,null,'/FINREPORTS/captacion/POS/ADQ/IN','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX')
/
COMMIT
/
Delete from custom.c_cpmaster where PARAMETER_ID = 'POS_PROSA_REQUEST' and BANK_ID = 'BAZMX'
/
Delete from custom.c_cpvalue where PARAMETER_ID = 'POS_PROSA_REQUEST' and BANK_ID = 'BAZMX'
/
Insert into custom.c_cpmaster (MODULE_NAME,PARAMETER_LEVEL,PARAMETER_ID,PARAMETER_DESC,PARAMETER_TYPE,QUERY_ID,LIST_TYPE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('LIABILITIES','BNKL','POS_PROSA_REQUEST','Debit Card JSON Response Path',
null,null,'FT','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX')
/
Insert into custom.c_cpvalue (PARAMETER_ID,LEVELCODE_1,LEVELCODE_2,PARAMETER_VALUE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('POS_PROSA_REQUEST',null,null,'/FINREPORTS/captacion/POS/PROSA/IN','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX')
/
COMMIT
/
Delete from custom.c_cpmaster where PARAMETER_ID = 'POS_EGLO_REQUEST' and BANK_ID = 'BAZMX'
/
Delete from custom.c_cpvalue where PARAMETER_ID = 'POS_EGLO_REQUEST' and BANK_ID = 'BAZMX'
/
Insert into custom.c_cpmaster (MODULE_NAME,PARAMETER_LEVEL,PARAMETER_ID,PARAMETER_DESC,PARAMETER_TYPE,QUERY_ID,LIST_TYPE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('LIABILITIES','BNKL','POS_EGLO_REQUEST','Debit Card Account Scheme Code',
null,null,'FT','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX')
/
Insert into custom.c_cpvalue (PARAMETER_ID,LEVELCODE_1,LEVELCODE_2,PARAMETER_VALUE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('POS_EGLO_REQUEST',null,null,'/FINREPORTS/captacion/POS/EGLO/IN','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX');
/
COMMIT
/
Delete from custom.c_cpmaster where PARAMETER_ID = 'POS_ADQUIRENTE_RESPONSE' and BANK_ID = 'BAZMX'
/
Delete from custom.c_cpvalue where PARAMETER_ID = 'POS_ADQUIRENTE_RESPONSE' and BANK_ID = 'BAZMX'
/
Insert into custom.c_cpmaster (MODULE_NAME,PARAMETER_LEVEL,PARAMETER_ID,PARAMETER_DESC,PARAMETER_TYPE,QUERY_ID,LIST_TYPE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('LIABILITIES','BNKL','POS_ADQUIRENTE_RESPONSE','Debit Card Product Structure.',
null,null,'FT','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX')
/
Insert into custom.c_cpvalue (PARAMETER_ID,LEVELCODE_1,LEVELCODE_2,PARAMETER_VALUE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('POS_ADQUIRENTE_RESPONSE',null,null,'/FINREPORTS/captacion/POS/ADQ/OUT','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX')
/
COMMIT
/
Delete from custom.c_cpmaster where PARAMETER_ID = 'POS_PROSA_RESPONSE' and BANK_ID = 'BAZMX'
/
Delete from custom.c_cpvalue where PARAMETER_ID = 'POS_PROSA_RESPONSE' and BANK_ID = 'BAZMX'
/
Insert into custom.c_cpmaster (MODULE_NAME,PARAMETER_LEVEL,PARAMETER_ID,PARAMETER_DESC,PARAMETER_TYPE,QUERY_ID,LIST_TYPE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('LIABILITIES','BNKL','POS_PROSA_RESPONSE','Channel ID for Debit Card file processing.',
null,null,'FT','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX')
/
Insert into custom.c_cpvalue (PARAMETER_ID,LEVELCODE_1,LEVELCODE_2,PARAMETER_VALUE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('POS_PROSA_RESPONSE',null,null,'/FINREPORTS/captacion/POS/PROSA/OUT','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX')
/
COMMIT
/
Delete from custom.c_cpmaster where PARAMETER_ID = 'POS_EGLO_RESPONSE' and BANK_ID = 'BAZMX'
/
Delete from custom.c_cpvalue where PARAMETER_ID = 'POS_EGLO_RESPONSE' and BANK_ID = 'BAZMX'
/
Insert into custom.c_cpmaster (MODULE_NAME,PARAMETER_LEVEL,PARAMETER_ID,PARAMETER_DESC,PARAMETER_TYPE,QUERY_ID,LIST_TYPE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('LIABILITIES','BNKL','POS_EGLO_RESPONSE','Channel ID for Debit Card file processing.',
null,null,'FT','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX')
/
Insert into custom.c_cpvalue(PARAMETER_ID,LEVELCODE_1,LEVELCODE_2,PARAMETER_VALUE,ENTITY_CRE_FLG,DEL_FLG,RCRE_USER_ID,RCRE_TIME,LCHG_USER_ID,LCHG_TIME,BANK_ID) values ('POS_EGLO_RESPONSE',null,null,'/FINREPORTS/captacion/POS/EGLO/OUT','Y','N','SYSTEM',SYSDATE,'SYSTEM',SYSDATE,'BAZMX')
/
COMMIT
/